image: debian:latest

before_script:
 - |
    apt-get update
    apt-get install -y build-essential
    apt-get install -y pkg-config
    apt-get install -y libglfw3 libglfw3-dev

stages:
  - build
            
build:
  stage: build
  script:
    - cd scenes/inf443/generator/
    - make